# Generated by Django 4.2.13 on 2024-05-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_appliedjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='experience',
            new_name='company_overview',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='ideal_candidate',
            new_name='post_overview',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(default='nothing to see', max_length=100),
            preserve_default=False,
        ),
    ]
